# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 621, 62))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.br_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.br_button.setMinimumSize(QtCore.QSize(0, 60))
        self.br_button.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.br_button.setFont(font)
        self.br_button.setObjectName("br_button")
        self.gridLayout.addWidget(self.br_button, 0, 3, 1, 1)
        self.falcon_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.falcon_button.sizePolicy().hasHeightForWidth())
        self.falcon_button.setSizePolicy(sizePolicy)
        self.falcon_button.setMinimumSize(QtCore.QSize(0, 60))
        self.falcon_button.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.falcon_button.setFont(font)
        self.falcon_button.setStyleSheet("QPushButton{color:blue};")
        self.falcon_button.setObjectName("falcon_button")
        self.gridLayout.addWidget(self.falcon_button, 0, 1, 1, 1)
        self.m100_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.m100_button.setMinimumSize(QtCore.QSize(0, 60))
        self.m100_button.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.m100_button.setFont(font)
        self.m100_button.setObjectName("m100_button")
        self.gridLayout.addWidget(self.m100_button, 0, 4, 1, 1)
        self.maxon_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.maxon_button.setMinimumSize(QtCore.QSize(0, 60))
        self.maxon_button.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.maxon_button.setFont(font)
        self.maxon_button.setObjectName("maxon_button")
        self.gridLayout.addWidget(self.maxon_button, 0, 5, 1, 1)
        self.savox_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.savox_button.setMinimumSize(QtCore.QSize(0, 60))
        self.savox_button.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.savox_button.setFont(font)
        self.savox_button.setObjectName("savox_button")
        self.gridLayout.addWidget(self.savox_button, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 621, 381))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.measured_velocity = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.measured_velocity.setFont(font)
        self.measured_velocity.setAlignment(QtCore.Qt.AlignCenter)
        self.measured_velocity.setObjectName("measured_velocity")
        self.verticalLayout_2.addWidget(self.measured_velocity)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.motor_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.motor_name.setFont(font)
        self.motor_name.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_name.setObjectName("motor_name")
        self.gridLayout_2.addWidget(self.motor_name, 0, 1, 1, 1)
        self.forward_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.forward_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.forward_button.setFont(font)
        self.forward_button.setObjectName("forward_button")
        self.gridLayout_2.addWidget(self.forward_button, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.set_velocity_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.set_velocity_label.setFont(font)
        self.set_velocity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.set_velocity_label.setObjectName("set_velocity_label")
        self.verticalLayout_3.addWidget(self.set_velocity_label)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("QPushButton{color:red};")
        self.stop_button.setCheckable(False)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 2, 0, 1, 1)
        self.reverse_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.reverse_button.setFont(font)
        self.reverse_button.setObjectName("reverse_button")
        self.gridLayout_2.addWidget(self.reverse_button, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vel_up = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.vel_up.setFont(font)
        self.vel_up.setObjectName("vel_up")
        self.horizontalLayout.addWidget(self.vel_up)
        self.vel_down = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.vel_down.setFont(font)
        self.vel_down.setObjectName("vel_down")
        self.horizontalLayout.addWidget(self.vel_down)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.vel_down.pressed.connect(MainWindow.down_velocity)
        self.reverse_button.pressed.connect(MainWindow.set_motor_state)
        self.vel_up.pressed.connect(MainWindow.up_velocity)
        self.forward_button.pressed.connect(MainWindow.set_motor_state)
        self.stop_button.pressed.connect(MainWindow.set_motor_state)
        self.falcon_button.pressed.connect(MainWindow.button_handler)
        self.br_button.pressed.connect(MainWindow.button_handler)
        self.m100_button.pressed.connect(MainWindow.button_handler)
        self.maxon_button.pressed.connect(MainWindow.button_handler)
        self.savox_button.pressed.connect(MainWindow.button_handler)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.br_button.setText(_translate("MainWindow", "Blue\n"
"Robotics"))
        self.falcon_button.setText(_translate("MainWindow", "Falcon\n"
"Pump"))
        self.m100_button.setText(_translate("MainWindow", "M100"))
        self.maxon_button.setText(_translate("MainWindow", "Maxon\n"
"Sensorless"))
        self.savox_button.setText(_translate("MainWindow", "Falcon\n"
"Savox"))
        self.label_3.setText(_translate("MainWindow", "Measured Velocity:"))
        self.measured_velocity.setText(_translate("MainWindow", "TextLabel"))
        self.motor_name.setText(_translate("MainWindow", "Falcon"))
        self.forward_button.setText(_translate("MainWindow", "Forward"))
        self.label_6.setText(_translate("MainWindow", "Set Velocity:"))
        self.set_velocity_label.setText(_translate("MainWindow", "TextLabel"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.reverse_button.setText(_translate("MainWindow", "Reverse"))
        self.vel_up.setText(_translate("MainWindow", "^"))
        self.vel_down.setText(_translate("MainWindow", "v"))

