# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_testWin(object):
    def setupUi(self, testWin):
        testWin.setObjectName("testWin")
        testWin.resize(320, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(testWin.sizePolicy().hasHeightForWidth())
        testWin.setSizePolicy(sizePolicy)
        testWin.setMinimumSize(QtCore.QSize(320, 240))
        testWin.setMaximumSize(QtCore.QSize(320, 400))
        self.centralWidget = QtWidgets.QWidget(testWin)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 311, 182))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.vl.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vl.setFont(font)
        self.vl.setAlignment(QtCore.Qt.AlignCenter)
        self.vl.setObjectName("vl")
        self.gridLayout_2.addWidget(self.vl, 4, 2, 1, 1)
        self.dp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dp.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dp.setFont(font)
        self.dp.setAlignment(QtCore.Qt.AlignCenter)
        self.dp.setObjectName("dp")
        self.gridLayout_2.addWidget(self.dp, 2, 3, 1, 1)
        self.cl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cl.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cl.setFont(font)
        self.cl.setAlignment(QtCore.Qt.AlignCenter)
        self.cl.setObjectName("cl")
        self.gridLayout_2.addWidget(self.cl, 4, 1, 1, 1)
        self.dl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dl.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dl.setFont(font)
        self.dl.setAlignment(QtCore.Qt.AlignCenter)
        self.dl.setObjectName("dl")
        self.gridLayout_2.addWidget(self.dl, 4, 3, 1, 1)
        self.mv_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mv_3.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mv_3.setFont(font)
        self.mv_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mv_3.setObjectName("mv_3")
        self.gridLayout_2.addWidget(self.mv_3, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.mv = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mv.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mv.setFont(font)
        self.mv.setAlignment(QtCore.Qt.AlignCenter)
        self.mv.setObjectName("mv")
        self.gridLayout_2.addWidget(self.mv, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.vp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.vp.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vp.setFont(font)
        self.vp.setAlignment(QtCore.Qt.AlignCenter)
        self.vp.setObjectName("vp")
        self.gridLayout_2.addWidget(self.vp, 2, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 7, 0, 1, 4)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 3, 0, 1, 4)
        self.mv_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mv_2.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mv_2.setFont(font)
        self.mv_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mv_2.setObjectName("mv_2")
        self.gridLayout_2.addWidget(self.mv_2, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 4)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 4)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 5, 0, 1, 4)
        self.cp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cp.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cp.setFont(font)
        self.cp.setAlignment(QtCore.Qt.AlignCenter)
        self.cp.setObjectName("cp")
        self.gridLayout_2.addWidget(self.cp, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ca = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ca.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ca.setFont(font)
        self.ca.setAlignment(QtCore.Qt.AlignCenter)
        self.ca.setObjectName("ca")
        self.horizontalLayout.addWidget(self.ca)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 11, 0, 1, 1)
        self.ch = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ch.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ch.setFont(font)
        self.ch.setAlignment(QtCore.Qt.AlignCenter)
        self.ch.setObjectName("ch")
        self.gridLayout_2.addWidget(self.ch, 8, 1, 1, 1)
        self.va = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.va.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.va.setFont(font)
        self.va.setAlignment(QtCore.Qt.AlignCenter)
        self.va.setObjectName("va")
        self.gridLayout_2.addWidget(self.va, 6, 2, 1, 1)
        self.vh = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.vh.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vh.setFont(font)
        self.vh.setAlignment(QtCore.Qt.AlignCenter)
        self.vh.setObjectName("vh")
        self.gridLayout_2.addWidget(self.vh, 8, 2, 1, 1)
        self.dh = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dh.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dh.setFont(font)
        self.dh.setAlignment(QtCore.Qt.AlignCenter)
        self.dh.setObjectName("dh")
        self.gridLayout_2.addWidget(self.dh, 8, 3, 1, 1)
        self.da = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.da.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.da.setFont(font)
        self.da.setAlignment(QtCore.Qt.AlignCenter)
        self.da.setObjectName("da")
        self.gridLayout_2.addWidget(self.da, 6, 3, 1, 1)
        self.exit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.exit.setObjectName("exit")
        self.gridLayout_2.addWidget(self.exit, 11, 3, 1, 1)
        self.start = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 11, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.time.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time.setFont(font)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.horizontalLayout_3.addWidget(self.time)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 11, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(280, 70, 105, 15))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        testWin.setCentralWidget(self.centralWidget)

        self.retranslateUi(testWin)
        self.exit.clicked.connect(testWin.exit_window)
        self.start.clicked.connect(testWin.start_stop_test)
        QtCore.QMetaObject.connectSlotsByName(testWin)

    def retranslateUi(self, testWin):
        _translate = QtCore.QCoreApplication.translate
        testWin.setWindowTitle(_translate("testWin", "MainWindow"))
        self.vl.setText(_translate("testWin", "-"))
        self.dp.setText(_translate("testWin", "-"))
        self.cl.setText(_translate("testWin", "-"))
        self.dl.setText(_translate("testWin", "-"))
        self.mv_3.setText(_translate("testWin", "Duty Cycle"))
        self.label_10.setText(_translate("testWin", "Present"))
        self.label_11.setText(_translate("testWin", "Min"))
        self.mv.setText(_translate("testWin", "Current"))
        self.label_9.setText(_translate("testWin", "Average"))
        self.label_8.setText(_translate("testWin", "Max"))
        self.vp.setText(_translate("testWin", "-"))
        self.mv_2.setText(_translate("testWin", "Velocity"))
        self.cp.setText(_translate("testWin", "-"))
        self.ca.setText(_translate("testWin", "-"))
        self.label_15.setText(_translate("testWin", "Time"))
        self.ch.setText(_translate("testWin", "-"))
        self.va.setText(_translate("testWin", "-"))
        self.vh.setText(_translate("testWin", "-"))
        self.dh.setText(_translate("testWin", "-"))
        self.da.setText(_translate("testWin", "-"))
        self.exit.setText(_translate("testWin", "Exit"))
        self.start.setText(_translate("testWin", "START"))
        self.time.setText(_translate("testWin", "-"))
        self.label_16.setText(_translate("testWin", "rpm"))

