# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variablewindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_varWin(object):
    def setupUi(self, varWin):
        varWin.setObjectName("varWin")
        varWin.resize(320, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(varWin.sizePolicy().hasHeightForWidth())
        varWin.setSizePolicy(sizePolicy)
        varWin.setMinimumSize(QtCore.QSize(320, 240))
        varWin.setMaximumSize(QtCore.QSize(320, 400))
        self.centralWidget = QtWidgets.QWidget(varWin)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, -2, 311, 182))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.fw = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.fw.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fw.setFont(font)
        self.fw.setAlignment(QtCore.Qt.AlignCenter)
        self.fw.setObjectName("fw")
        self.gridLayout_2.addWidget(self.fw, 8, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.dc = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dc.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dc.setFont(font)
        self.dc.setAlignment(QtCore.Qt.AlignCenter)
        self.dc.setObjectName("dc")
        self.gridLayout_2.addWidget(self.dc, 2, 1, 1, 1)
        self.mv = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mv.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mv.setFont(font)
        self.mv.setAlignment(QtCore.Qt.AlignCenter)
        self.mv.setObjectName("mv")
        self.gridLayout_2.addWidget(self.mv, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.mc = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mc.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mc.setFont(font)
        self.mc.setAlignment(QtCore.Qt.AlignCenter)
        self.mc.setObjectName("mc")
        self.gridLayout_2.addWidget(self.mc, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 7, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 3, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 6, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 8, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 5, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 10, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.kp.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kp.setFont(font)
        self.kp.setAlignment(QtCore.Qt.AlignCenter)
        self.kp.setObjectName("kp")
        self.horizontalLayout.addWidget(self.kp)
        self.ki = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ki.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ki.setFont(font)
        self.ki.setAlignment(QtCore.Qt.AlignCenter)
        self.ki.setObjectName("ki")
        self.horizontalLayout.addWidget(self.ki)
        self.kd = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.kd.setMaximumSize(QtCore.QSize(16777215, 99999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kd.setFont(font)
        self.kd.setAlignment(QtCore.Qt.AlignCenter)
        self.kd.setObjectName("kd")
        self.horizontalLayout.addWidget(self.kd)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(280, 70, 105, 15))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        varWin.setCentralWidget(self.centralWidget)

        self.retranslateUi(varWin)
        self.pushButton.clicked.connect(varWin.exit_window)
        QtCore.QMetaObject.connectSlotsByName(varWin)

    def retranslateUi(self, varWin):
        _translate = QtCore.QCoreApplication.translate
        varWin.setWindowTitle(_translate("varWin", "MainWindow"))
        self.label_10.setText(_translate("varWin", "Duty Cycle"))
        self.fw.setText(_translate("varWin", "TextLabel"))
        self.label_11.setText(_translate("varWin", "Measured Current"))
        self.dc.setText(_translate("varWin", "TextLabel"))
        self.mv.setText(_translate("varWin", "TextLabel"))
        self.label_12.setText(_translate("varWin", "Motor Velocity"))
        self.label_9.setText(_translate("varWin", "P,I,D"))
        self.mc.setText(_translate("varWin", "TextLabel"))
        self.label_8.setText(_translate("varWin", "FW Revision"))
        self.label_13.setText(_translate("varWin", "rpm"))
        self.label_14.setText(_translate("varWin", "%"))
        self.label_18.setText(_translate("varWin", "mA"))
        self.pushButton.setText(_translate("varWin", "Exit"))
        self.kp.setText(_translate("varWin", "TextLabel"))
        self.ki.setText(_translate("varWin", "TextLabel"))
        self.kd.setText(_translate("varWin", "TextLabel"))
        self.label_16.setText(_translate("varWin", "rpm"))

